### ISSUE TITLE
Valid formats not parsed correctly

### ISSUE THREAD

**Issue by tozka** [ethlo/itu#3]
2016-04-27T11:30:24.952123456 and 2016-04-27T11:30:24.952123 are valid formats  but throw expections

Caused by: java.time.DateTimeException: Invalid timezone offset: 952123456
	at com.ethlo.time.FastInternetDateTimeUtil.parseTz(FastInternetDateTimeUtil.java:99)
	at com.ethlo.time.FastInternetDateTimeUtil.seconds(FastInternetDateTimeUtil.java:383)
	at com.ethlo.time.FastInternetDateTimeUtil.doParseLenient(FastInternetDateTimeUtil.java:331)
	at com.ethlo.time.FastInternetDateTimeUtil.parseDateTime(FastInternetDateTimeUtil.java:53)

**Comment by ethlo** [comment]
The format you have presented is not valid as it does not contain a timezone offset or Z.

**Comment by tozka** [comment]
> The format you have presented is not valid as it does not contain a timezone offset or Z.

According to google 
https://stackoverflow.com/questions/33114386/datetime-iso-8601-without-timezone-component

"The zone designator is empty if use is made of local time in accordance with 4.2.2.2 through 4.2.2.4, it is the UTC designator [Z] if use is made of UTC of day in accordance with 4.2.4 and it is the difference-component if use is made of local time and the difference from UTC in accordance with 4.2.5.2."

**Comment by ethlo** [comment]
This is not a generic iso8601 parser. This is an rfc3339 parser. I have tried to document this in the readme, if something is not clear I apologize.

**Comment by tozka** [comment]
Yes, you are right. I do not know why I equate them in my head. 
It would be nice to have library that parses and formats data according to ISO but I realize that's it's a bit hard to make.

**Comment by ethlo** [comment]
Yes, I guess that would be nice, but IMHO the ISO8601 is borderline useless for its massive possibilities. That is why I (and much of the web-dev community) are very fond of RFC3339, as it is a nicely limited format that conveys the date-time in a non-ambiguous way. Thanks for your interest!
